### ISSUE TITLE
Tabs are also displayed when assigning a product page layout, but only Tab1 works (tabs 2,3,4,5... missing in frontend)

### ISSUE THREAD

**Issue by lveith** [sschreier/SschreierTabProductDetailPage#1]
When you manually assigning any product-layout in a product,
than only Tab1 displayed in frontend
and other Tabs not!

When No-Layout is manually assigned to a product,
shopware uses auto-fallback to "Default product page Layout"
this worked with any tabs in frontend 1,2,3,4,5 (ok).

If manually assigning in a product any layout (not using auto-fallback by Null-Defintion in cms-page)
than always only Tab1 worked and others not.
Tested with manually assingning own new Layout "myProductLayout"
and with manually assingning  "Default product page Layout".
Both only shown only Tab1 in frontend, what means it comes by manually assigning and not by manually creating new own layout.
It is a different between auto-fallback to "Default product page Layout"
and manually assingning  "Default product page Layout".

Hope my info helps a little bit.
Tested with a fresh created shop without any other plugins
shopware v6.4.16.0

**Comment by berenssolutions** [comment]
can confirm, something is conflicting with the layout assignment on the product page.
with default layout (layout deleted basically) it works. i will further look into it tomorrow and provide more details.
By the way, thanks for the plugin!

**Comment by zarkas6** [comment]
Same issue here. Any solution to this otherwise pretty good plugin?

**Comment by sschreier** [comment]
Solved with version 1.1.1: https://github.com/sschreier/SschreierTabProductDetailPage/commit/eb26e292e7b8f0d0c7119134663af28734e253ad .
