### ISSUE TITLE
tab content appears twice on mobile, offcanvas and below the tab titles

### ISSUE THREAD

**Issue by openmindculture** [sschreier/SschreierTabProductDetailPage#2]
tab content appears twice on mobile: in offcanvas and below the tab titles

![screenshot collage](https://github.com/sschreier/SschreierTabProductDetailPage/assets/6377941/80130951-3ed0-4a39-be07-efff550de31b)

**Comment by sschreier** [comment]
Hello,

thanks for your message.

Unfortunately that's not true. It's only the same plain text if the content does not contain HTML code and the number of characters (which can be set in the configuration: https://github.com/sschreier/SschreierTabProductDetailPage/blob/master/src/Resources/config/config.xml#L18 ) from which the preview text should be truncated in the smaller resolutions has not yet been reached. The same behavior you also have in the "Description" tab, which exists in the standard of Shopware 6.

**Comment by openmindculture** [comment]
That sounds factually true, although it does not feel like good UX, but that's not your fault.
Do you have any hint for further documentation beyond the official docs and academy training? Details like this, or how to use offcanvas for tabs correctly doesn't seem documented well, and even Shopware employees in Slack told me to look for examples in other people's plugins (like your excellent example) to see how it has to be done?

**Comment by sschreier** [comment]
In your opinion, what would be good UX in the case when the tab content only has a few characters? The content would not be opened in OffCanvas? This is not intended by Shopware.

You can set the number of characters for the preview to, for example, 5, then it would almost never be identical.

My implementation is the solution intended by Shopware and implemented by Shopware for example for the description tab, so you will not find any other documentation for this case. The best documentation is the code used by Shopware.

**Comment by sschreier** [comment]
Examples from Shopware for individual topics can be found at https://developer.shopware.com/docs/guides/plugins/plugins/storefront/

**Comment by openmindculture** [comment]
Thanks for your quick replies and explanation!
